version: "3.7"

services:
  nifi:
    build:
      context: .
    container_name: nifi
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_WEB_HTTPS_PORT=8443
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - nifi_net
    # If needed, add volume mappings or custom configuration

networks:
  nifi_net:
    external: true
