version: '3'

services:
  superset-metadata-db:
    image: postgres:14
    container_name: superset-metadata-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER_SUPERSET}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SUPERSET}
      POSTGRES_DB: ${POSTGRES_DB_SUPERSET}
    volumes:
      - superset_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - superset_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_SUPERSET} -d ${POSTGRES_DB_SUPERSET}"]
      interval: 15s
      timeout: 5s
      retries: 8
      start_period: 30s

  superset:
    build:
      context: .
    container_name: superset
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_SUPERSET}
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI_SUPERSET}
    depends_on:
      superset-metadata-db:
        condition: service_healthy
    restart: always
    ports:
      - "8088:8088"
    networks:
      - superset_network
    healthcheck:
      test: ["CMD", "python3", "-c", "import http.client; conn = http.client.HTTPConnection('localhost', 8088); conn.request('GET', '/health'); response = conn.getresponse(); exit(0) if response.status == 200 else exit(1)"]
      interval: 10s
      timeout: 10s
      retries: 25
      start_period: 30s

networks:
  superset_network:

volumes:
  superset_db_data:
