version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - data_pipeline_net
    healthcheck:
      test: ["CMD-SHELL", "mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e 'SHOW DATABASES;' || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 30
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - data_pipeline_net
    healthcheck:
      test: ["CMD", "curl", "-Ss", "http://localhost/robots.txt"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

networks:
  data_pipeline_net:
    external: false

volumes:
  mysql_data:
