version: '3.8'

services:
  jobmanager:
    image: apache/flink:1.16.0
    container_name: flink-jobmanager
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=${FLINK_JOB_MANAGER_RPC_ADDRESS}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${FLINK_JOB_MANAGER_RPC_ADDRESS}
    ports:
      - "8081:8081"   # Flink Web UI
    networks:
      - flink-network
    volumes:
      - jobmanager-logs:/opt/flink/log
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/taskmanagers"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  taskmanager:
    image: apache/flink:1.16.0
    container_name: flink-taskmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=${FLINK_JOB_MANAGER_RPC_ADDRESS}
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: ${FLINK_JOB_MANAGER_RPC_ADDRESS}
    depends_on:
      jobmanager:
        condition: service_healthy
    restart: always
    networks:
      - flink-network
    volumes:
      - taskmanager-logs:/opt/flink/log
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep -q 'taskmanager'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s




networks:
  flink-network:
    driver: bridge

volumes:
  jobmanager-logs:
  taskmanager-logs:
