version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER_PG}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_PG}
      POSTGRES_DB: ${POSTGRES_DB_PG}
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - data_pipeline_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER_PG} -d $${POSTGRES_DB_PG}"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - data_pipeline_net
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -q --spider http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

networks:
  data_pipeline_net:
    driver: bridge

volumes:
  postgres_data:
